### ISSUE TITLE
CPU can't read from 2K ram at $7800

### ISSUE THREAD

**Issue by RedskullDC** [MiSTer-devel/Laser310_MiSTer#1]
LASER310_TOP.v is missing a case to read from the 2k ram @ $7800.

Needs the highlighted line added:

assign CPU_DI = 	
				ADDRESS_ROM		? SYS_ROM_DATA		:
				ADDRESS_AUTOSTARTROM	? AUTOSTART_ROM_DATA	:
				ADDRESS_DOSROM		? DOS_ROM_DATA		:
				**_ADDRESS_RAM_78		? RAM_78_DATA		:_**

**Comment by alanswx** [comment]
Good catch.

**Comment by alanswx** [comment]
How do I test this?

**Comment by RedskullDC** [comment]
Easiest way is to use poke/peek commands from BASIC on the $7800-$7FFF area.
example: (7fff)
Poke 32767,55
print peek (32767)

what comes back?
