### ISSUE TITLE
No cursor on Basic prompt

### ISSUE THREAD

**Issue by retrocrypta** [MiSTer-devel/Laser310_MiSTer#3]
The core starts with the screen full of at symbols. @ 
The core seems to work but it's weird. 
No cursor is present at Basic prompt. No cursor even in DOS mode.
The core writes when typing

**Comment by alanswx** [comment]
Good catch. I had the wrong font - I was using the Alice font instead of the Laser font. There are still problems with this core, and I am not sure the video and timing is quite right.
